-- Custom Types
CREATE TYPE public.user_role AS ENUM ('admin', 'agent', 'supervisor');

-- Companies Table
create table public.companies (
  id bigint generated by default as identity not null,
  name text not null,
  created_at timestamp with time zone null default now(),
  constraint companies_pkey primary key (id),
  constraint companies_name_key unique (name)
) TABLESPACE pg_default;

-- Units Table
create table public.units (
  id bigint generated by default as identity not null,
  company_id bigint null,
  building_name text null,
  unit_number text null,
  layout text null,
  door_code text null,
  constraint units_pkey primary key (id),
  constraint units_company_id_unit_number_key unique (company_id, unit_number),
  constraint units_company_id_fkey foreign KEY (company_id) references companies (id) on delete CASCADE
) TABLESPACE pg_default;

-- Profiles Table (for employees/users)
create table public.profiles (
  id uuid not null,
  username text null,
  full_name text null,
  role public.user_role null default 'agent'::user_role,
  created_at timestamp with time zone null default now(),
  avatar_url text null,
  phone text null,
  last_login timestamp with time zone null,
  status text null default 'active'::text,
  constraint profiles_pkey primary key (id),
  constraint profiles_username_key unique (username),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

-- Teams Table
create table public.teams (
  id bigint generated by default as identity not null,
  team_name text null,
  member_ids uuid[] null default '{}'::uuid[],
  created_at timestamp with time zone null default now(),
  status text null default 'active'::text,
  shift_date date null default CURRENT_DATE,
  updated_at timestamp with time zone null default now(),
  constraint teams_pkey primary key (id)
) TABLESPACE pg_default;

-- Bookings Table
create table public.bookings (
  id bigint generated by default as identity not null,
  unit_id bigint null,
  cleaning_date date not null,
  cleaning_time time without time zone null,
  service_type text null,
  status text null default 'pending'::text,
  created_at timestamp with time zone null default now(),
  assigned_team_id bigint null,
  price numeric(10, 2) null default 0,
  invoice_no text null,
  constraint bookings_pkey primary key (id),
  constraint bookings_assigned_team_id_fkey foreign KEY (assigned_team_id) references teams (id),
  constraint bookings_unit_id_fkey foreign KEY (unit_id) references units (id)
) TABLESPACE pg_default;

-- Checklist Templates Table
create table public.checklist_templates (
  id bigint generated by default as identity not null,
  title text not null,
  description text null,
  content jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone null default now(),
  constraint checklist_templates_pkey primary key (id)
) TABLESPACE pg_default;

-- Work Logs Table
create table public.work_logs (
  id bigint generated by default as identity not null,
  booking_id bigint null,
  team_id bigint null,
  start_time timestamp with time zone null,
  end_time timestamp with time zone null,
  checklist_data jsonb null,
  photo_urls text[] null default '{}'::text[],
  cost numeric(10, 2) null,
  submitted_by uuid null,
  constraint work_logs_pkey primary key (id),
  constraint work_logs_booking_id_fkey foreign KEY (booking_id) references bookings (id),
  constraint work_logs_submitted_by_fkey foreign KEY (submitted_by) references profiles (id),
  constraint work_logs_team_id_fkey foreign KEY (team_id) references teams (id)
) TABLESPACE pg_default;
